export const MachineLearningAdvanceModules = [
  {
    ModuleName: "Module 1",
    title: "Introduction to Machine Learning",
    topics: [
      "What is Machine Learning?",
      "Supervised Learning (context)",
      "Intuition of Machine Learning",
      "Various examples of ML",
      "Supervised Learning (context)",
      "Vectors/Matrices (quick overview)",
      "Introduction",
      "Add, Subtract",
      "Scalar Multiplication",
      "Vector Multiplication",
      "Inverse, Transpose",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Learning with Regression",
    topics: [
      "Intuition & Representation",
      "Understanding Cost Function",
      "What is Cost",
      "Function of Cost and minimization objective",
      "Intuition of cost with various examples",
      "Representating and Visualization CF",
      "Gradient Descent: Intuition",
      "Multivariate Linear Regression",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Logistic Regression",
    topics: [
      "Motivation and Examples",
      "Understanding classification",
      "Understanding the model",
      "Intuition behind decision boundary - seeing how classification is made. how the decision boundary is computed",
      "Logistic Cost Function",
      "Cost Function for logistic regression",
      "Point out that Gradient Descent is the same here as well",
      "Multiclass classification",
    ],
  },
  {
    ModuleName: "Module 4",
    title: "Regularization & Evaluation",
    topics: [
      "Understanding overfitting and underfitting",
      "Evaluating a model",
      "Regularization",
      "Understanding how regularization affects learning",
      "Bias & Variance",
      "Error Analysis",
    ],
  },
  {
    ModuleName: "Module 5",
    title: "Neural Networks and Advanced Topics",
    topics: [
      "Intuition",
      "Fundamentals of Neural Networks",
      "Why Neural Networks",
      "Representation",
      "Model Structuring",
      "Nomenclature",
      "Sample network",
      "Vectorization",
      "NN in classification",
      "NN learning",
      "Additional Types of Networks",
      "Introduction to Transfer Learning",
    ],
  },
  {
    ModuleName: "Module 6",
    title: "Introduction to TensorFlow",
    topics: [
      "What is TensorFlow",
      "Key points",
      "Gist of Keras and TF",
      "Overview of components",
      "Activation Functions",
      "Gist to other functions",
      "Simple Neural Network",
      "Multi-class Neural Network 5",
    ],
  },
  {
    ModuleName: "Module 7",
    title: "Decision Trees",
    topics: [
      "Introduction",
      "Intuition Behind decision trees",
      "Learning Process",
      "Purity Check",
      "Information Gain",
      "Handling Continuous features",
      "Handling Categorical features",
      "Random Forest Algorithm",
      "Intuition of using multiple trees",
      "Random Forest concept",
      "Concept of XGBoost trees",
    ],
  },
  {
    ModuleName: "Module 8",
    title: "Unsupervised Learning",
    topics: [
      "Introduction to Unsupervised learning",
      "Fundamentals of Neural Networks",
      "What is Clustering",
      "K-means intuition",
      "K-means process",
      "Understanding Clusters",
      "Finding patterns",
      "Intuition",
      "Understanding development of anomaly detection - Difference to Supervised learning",
    ],
  },
];
export const MachineLearningBasicModules = [
  {
    ModuleName: "Module 1",
    title: "Introduction to Machine Learning",
    topics: [
      "What is Machine Learning?",
      "Supervised Learning (context)",
      "Intuition of Machine Learning",
      "Various examples of ML",
      "Supervised Learning (context)",
      "Vectors/Matrices (quick overview)",
      "Introduction",
      "Add, Subtract",
      "Scalar Multiplication",
      "Vector Multiplication",
      "Inverse, Transpose",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Learning with Regression",
    topics: [
      "Intuition & Representation",
      "Understanding Cost Function",
      "What is Cost",
      "Function of Cost and minimization objective",
      "Intuition of cost with various examples",
      "Representating and Visualization CF",
      "Gradient Descent: Intuition",
      "Multivariate Linear Regression",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Logistic Regression",
    topics: [
      "Motivation and Examples",
      "Understanding classification",
      "Understanding the model",
      "Intuition behind decision boundary - seeing how classification is made. how the decision boundary is computed",
      "Logistic Cost Function",
      "Cost Function for logistic regression",
      "Point out that Gradient Descent is the same here as well",
      "Multiclass classification",
    ],
  },
  {
    ModuleName: "Module 4",
    title: "Regularization & Evaluation",
    topics: [
      "Understanding overfitting and underfitting",
      "Evaluating a model",
      "Regularization",
      "Understanding how regularization affects learning",
      "Bias & Variance",
      "Error Analysis",
    ],
  },
  {
    ModuleName: "Module 5",
    title: "Neural Networks and Advanced Topics",
    topics: [
      "Intuition",
      "Fundamentals of Neural Networks",
      "Why Neural Networks",
      "Representation",
      "Model Structuring",
      "Nomenclature",
      "Sample network",
      "Vectorization",
      "NN in classification",
      "NN learning",
      "Additional Types of Networks",
      "Introduction to Transfer Learning",
    ],
  },
  {
    ModuleName: "Module 6",
    title: "Introduction to TensorFlow",
    topics: [
      "What is TensorFlow",
      "Key points",
      "Gist of Keras and TF",
      "Overview of components",
      "Activation Functions",
      "Gist to other functions",
      "Simple Neural Network",
      "Multi-class Neural Network 5",
    ],
  },
];
