export const UIAdvanceModules = [
  {
    ModuleName: "Module 1",
    title: "Understanding UI/UX Design",
    topics: [
      "Introduction to UI/UX Design",
      "Understanding UI/UX Design",
      "Definitions: What is UI (User Interface) Design? What is UX (User Experience) Design?",
      "Importance: The role of UI/UX in product development",
      "Real-world Examples: Examples of good and bad UI/UX design",
      "Key Concepts:",
      "UI vs UX: Differences and overlaps",
      "Roles and Responsibilities: The role of a UI/UX designer in a team",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Design Principles",
    topics: [
      "UI Design Principles",
      "Visual Hierarchy",
      "Consistency",
      "Typography",
      "Color Theory",
      "Spacing",
      "UX Design Principles",
      "Usability",
      "Accessibility",
      "User-centered Design",
      "Affordance",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Design Process",
    topics: [
      "Steps in the Design Process",
      "Research: Understanding users and the market",
      "Ideation: Brainstorming and sketching ideas",
      "Wireframing: Creating low-fidelity wireframes",
      "Prototyping: Developing interactive prototypes",
      "Testing: Conducting user testing and gathering feedback",
      "Creating Wireframes",
      "Definition and importance",
      "Hands-on Exercise: Create wireframes for a simple app",
    ],
  },
  {
    ModuleName: "Module 4",
    title: "Visual Design and Tools",
    topics: [
      "Visual Design",
      "Color Schemes",
      "Typography Choices",
      "Imagery and Icons",
      "Introduction to Figma",
      "Account Creation and Setup",
      "Basic Tools and Interface Overview",
      "Creating Frames, Shapes, and Text",
      "Prototyping in Figma",
      "Collaboration Features",
    ],
  },
  {
    ModuleName: "Module 5",
    title: "Current Trends and AI Integration",
    topics: [
      "UI/UX Design Trends 2024",
      "Minimalist Design",
      "Micro-interactions",
      "Voice User Interfaces (VUIs)",
      "AI Integration",
      "Generative AI and GPT Tools",
      "Overview of Generative AI in Design",
      "Using GPT-4 for Content Creation, Ideation, and User Interaction",
      "Case Studies of AI-enhanced UI/UX Design",
    ],
  },
  {
    ModuleName: "Module 6",
    title: "Advanced Topics and Case Studies",
    topics: [
      "Advanced UI/UX Topics",
      "Design Systems",
      "Responsive Design",
      "Mobile vs Web Design Considerations",
      "Case Studies",
      "Successful UI/UX Design Projects",
      "Lessons Learned from Real-world Applications",
    ],
  },
];
export const UIBasicModules = [
  {
    ModuleName: "Module 1",
    title: "Understanding UI/UX Design",
    topics: [
      "Introduction to UI/UX Design",
      "Understanding UI/UX Design",
      "Definitions: What is UI (User Interface) Design? What is UX (User Experience) Design?",
      "Importance: The role of UI/UX in product development",
      "Real-world Examples: Examples of good and bad UI/UX design",
      "Key Concepts:",
      "UI vs UX: Differences and overlaps",
      "Roles and Responsibilities: The role of a UI/UX designer in a team",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Design Principles",
    topics: [
      "UI Design Principles",
      "Visual Hierarchy",
      "Consistency",
      "Typography",
      "Color Theory",
      "Spacing",
      "UX Design Principles",
      "Usability",
      "Accessibility",
      "User-centered Design",
      "Affordance",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Design Process",
    topics: [
      "Steps in the Design Process",
      "Research: Understanding users and the market",
      "Ideation: Brainstorming and sketching ideas",
      "Wireframing: Creating low-fidelity wireframes",
      "Prototyping: Developing interactive prototypes",
      "Testing: Conducting user testing and gathering feedback",
      "Creating Wireframes",
      "Definition and importance",
      "Hands-on Exercise: Create wireframes for a simple app",
    ],
  },
  {
    ModuleName: "Module 4",
    title: "Visual Design and Tools",
    topics: [
      "Visual Design",
      "Color Schemes",
      "Typography Choices",
      "Imagery and Icons",
      "Introduction to Figma",
      "Account Creation and Setup",
      "Basic Tools and Interface Overview",
      "Creating Frames, Shapes, and Text",
      "Prototyping in Figma",
      "Collaboration Features",
    ],
  },
];
