export const DigitalMarketingAdvanceModules = [
  {
    ModuleName: "Week 9",
    title: "Introduction to Digital Marketing",
    topics: [
      "Blog / Business Website / E-Commerce Ranking Case Studies",
      "Meta Ads Setup, Page Creation, Targeting, & Retargeting",
      "Live Ads Creation (WhatsApp, Instagram, Messenger, etc.)",
      "Meta Pixel Setup, Payments & GST",
      "Google Ads Setup, Search Campaigns, YouTube Ads",
      "Shopping Ads, Google Merchant Center Setup",
      "Key Metrics, A/B Testing, Audience Segments",
    ],
  },
  {
    ModuleName: "Week 10",
    title: "Mobile & E-Commerce Marketing",
    topics: [
      "Mobile Website Optimization / ASO / IVR / SMS",
      "KPIs for Ecommerce, Product Listing",
      "Ecommerce Strategy, Competitor Ads, Best-Selling Products",
      "Flipkart & Amazon Seller Setup / Scaling Strategies",
      "Creating Blueprint of Every Web Page",
      "Website Design and Elementor",
      "Content Adding Plugins for Building Website",
      "Optimization of Web Pages",
    ],
  },
  {
    ModuleName: "Week 11",
    title: "Video Content & Social Media Strategy",
    topics: [
      "Explainer, Testimonial, Demo Scripts",
      "Social Media Reels / Shorts - Planning & Strategy",
      "Video Marketing for Brand Awareness",
      "Content Creation for Social Media Platforms",
      "Video SEO Optimization",
      "Video Distribution & Engagement Strategies",
      "Storytelling & Video Content Strategy",
      "Live Streaming & Interactive Content for Engagement",
    ],
  },
  {
    ModuleName: "Week 12",
    title: "Dropshipping, Affiliate & Freelancing Mastery",
    topics: [
      "Dropshipping: Product Research / Store Setup / Tracking / Scaling",
      "Affiliate Marketing: Affiliate Programs / Content Creation / Traffic Generation",
      "Affiliate Tools & SEO/Ads Campaign Strategy",
      "Freelancing: Account Setup / Client Pitching / Proposal Writing",
      "Self Project Case Studies / Personal Branding",
      "Drop Service: Building & Scaling Your Service-based Business",
      "Product Sourcing & Supplier Negotiation for Dropshipping",
      "Setting Up a Profitable Affiliate Marketing Funnel",
      "Affiliate Marketing Tools: SEO, Content Creation, Traffic Generation",
    ],
  },
  {
    ModuleName: "Week 13",
    title: "AI Tools in Marketing & Automation",
    topics: [
      "AI for Content Creation: Writing Tools, Generators",
      "AI for SEO: Optimization & Automation Tools",
      "AI for Video Marketing: Editing & Distribution",
      "AI for Ads Optimization: Dynamic Ads & Campaign Adjustments",
      "AI for Customer Engagement: Chatbots, Predictive Analytics",
      "AI Tools for Social Media Management",
      "AI Automation for Marketing Campaigns",
      "Voice Search Optimization with AI",
    ],
  },
  {
    ModuleName: "Week 14",
    title: "Funnel Building & Conversion Optimization (CRO)",
    topics: [
      "High-Converting Funnel Strategies: Understanding Funnel Types",
      "Building a Lead Generation Funnel",
      "Sales Funnel Design and Optimization",
      "Using Automation to Nurture Leads Through Funnels",
      "Optimizing Landing Pages for Higher Conversions",
      "A/B Testing for Funnel Optimization",
      "Behavioral Targeting & Dynamic Funnels",
      "Conversion Rate Optimization Tools and Techniques",
    ],
  },
  {
    ModuleName: "Week 15",
    title: "Online Reputation Management (ORM) & Influencer Marketing",
    topics: [
      "ORM Tools: Tracking Mentions and Sentiment Analysis",
      "Content Strategy for ORM: Blogging, Reviews, Social Media",
      "Managing Negative Reviews & Building Positive Reputation",
      "Influencer Marketing: Identifying and Collaborating with Influencers",
      "Developing an Influencer Marketing Strategy",
      "Social Proof & User-Generated Content (UGC)",
      "Building Trust and Credibility through ORM",
      "ORM in Crisis Management: Maintaining Brand Integrity",
    ],
  },
  {
    ModuleName: "Week 16",
    title: "Portfolio & Career Preparation",
    topics: [
      "Certification / Test / Assignment / Portfolio Building",
      "Doubt Sessions for Final Clarifications",
      "Final Project Preparation: Assignments and Real-World Applications",
      "Resume Building & Optimization for Digital Marketing Careers",
      "Mock Interviews: Behavioral, Technical, & Case Study",
      "Job Interview Preparation: Industry-Specific Questions",
      "Personal Branding & Networking for Job Search",
      "Job Portals: Creating a Strong Online Presence on LinkedIn, Glassdoor, etc.",
      "Final CIIM Certification - Meta, Google Ads, SEO",
      "Industry-Specific Interview Prep: Google, Meta, Hubspot, LinkedIn Learning",
      "Post-Course Career Support: Freelancing, Consulting, Full-Time Job Search",
    ],
  },
];
export const DigitalMarketingBasicModules = [
  {
    ModuleName: "Week 1",
    title: "Introduction to Digital Marketing",
    topics: [
      "Student orientation, Trainer intro",
      "Introduction to Marketing and Digital Marketing",
      "Traditional Vs Digital",
      "Benefits, Scope, Jobs, Freelancing, Earning",
      "Business Owner & Student Career Opportunities, Demand",
      "Digital Marketing - Organic Methods & Paid Methods Explained",
      "Digital Marketing Important Metrics Explanations",
    ],
  },
  {
    ModuleName: "Week 2",
    title: "Wordpress Website Planning & Development",
    topics: [
      "What is Domain, Hosting & Domain Extensions",
      "Domain Research, How to Buy",
      "How to Install a WordPress - For Beginners | Simple & Easy Steps",
      "Exploring the WordPress Dashboard Features & Installing Theme / Plugins",
      "How to Customize WordPress Theme - Step by Step Guide",
      "How to Create & Edit a Page in WordPress with Elementor & Add to Menu",
      "How to Design Perfect Homepage / Final Business Website Changes / Form Setup",
      "E-Commerce Website Development - Theme and Plugin Installation",
      "How to Create Header and Footer",
      "How to Design Homepage / How to Add Products",
      "Shipping & Payment Gateway Solutions for E-Commerce / Shopping Website",
    ],
  },
  {
    ModuleName: "Week 3",
    title: "Canva Graphic Design / Video Editing",
    topics: [
      "Introduction to Canva & Understanding Its Purpose and Benefits",
      "Understanding Templates, Elements, and Uploads for Ads & Posting Content",
      "Final Tips and Tricks / Time-Saving Hacks and Shortcuts",
      "Getting Started with Canva Video Editor / Editing Tool / Adding Visual Elements",
      "Adding Text Overlays, Customizing Fonts, Colors, Effects / Timeline and Layout",
    ],
  },
  {
    ModuleName: "Week 4",
    title: "Content Writing Strategies / Topic Selection",
    topics: [
      "Introduction to Niche and Content Writing",
      "Niche Selection & Categories / High Paying Niches",
      "Using Keyword Planner Tools for Keyword Research / Keyword Selection",
      "How to Write SEO Friendly Content Techniques",
      "How to Earn Money from Content Writing & Freelancing",
    ],
  },
  {
    ModuleName: "Week 5",
    title: "Search Engine Optimization / SEO",
    topics: [
      "What is SEO and How Does It Work?",
      "Types of SEO, Search Engine Overview",
      "SEO Plugins",
      "Updating Content on Website - As a Post",
      "Keyword Density, Slug, Meta Tags, Internal/External Links, Meta Tag Descriptions",
      "Alt Tag, Content Optimization, Category Creation, Blog Menu Setup",
      "Setting up a Blogging Website for Content Blogging & Earning",
      "Blogging Research Ideas",
      "Connecting Website with Google Search Console",
      "Dashboard Overview - Indexing / Crawling",
      "Google Search Console Features for SEO - Writing to Ranking",
      "Connecting Google Analytics with Website",
      "Google Analytics Dashboard & Features for Performance Optimization",
    ],
  },
  {
    ModuleName: "Week 6",
    title: "Off-Page SEO",
    topics: [
      "What is Off-Page SEO / Importance / Activities",
      "Role of Backlinks in SEO",
      "Types of Backlinks, Backlink Audit, Creation Process",
      "Day 1 - Social Media Bookmarking / Sharing / Business Listing / NAP Citations",
      "Day 2 - Blog Submission / Video Submission",
      "Day 3 - PDF & PPT Submission / Q&A Submission",
      "Day 4 - Guest Posting / Brand Mentions",
      "Off-page SEO Ranking Strategy Master Session / Backlink Building Techniques",
    ],
  },
  {
    ModuleName: "Week 7",
    title: "Local SEO",
    topics: [
      "How Local SEO Works / Local SEO Keywords",
      "Google Business Profile Listing & Ranking Factors",
      "Local SEO Ranking Guide in Detail",
    ],
  },
  {
    ModuleName: "Week 8",
    title: "Technical SEO",
    topics: [
      "Website Architecture and Crawlability",
      "Mobile-Friendliness",
      "Page Speed Optimization",
      "HTTPS / URL Structure Optimization / Schema Markup",
      "Duplicate Content, Technical Tools, International SEO, SEO Audit",
      "Ranking Website in 1 Month - Personalized Strategies",
    ],
  },
];
