export const IndianPlans = [
  {
    name: "Self Paced",
    price: "₹4499",
    originalPrice: "₹6399",
    tag: "MOST POPULAR",
    features: [
      "Training Certificate",
      "Certificate of Internship",
      "Capstone Project",
      "Industry Level Project",
      "4 Weeks Training",
      "4 Weeks Internship",
    ],
    buttonText: "Get Self Paced",
    buttonLink: "https://pages.razorpay.com/ps012024",
    maxWidth: "380px",
    maxHeight: "700px",
    minWidth: "380px",
    minHeight: "700px",
  },
  {
    name: "Pro Learning",
    price: "₹6499",
    originalPrice: "₹10800",
    tag: "MOST POPULAR",
    features: [
      "Training Certificate",
      "Certificate of Internship",
      "Capstone Project",
      "Industry Level Project",
      "6 Weeks Training",
      "6 Weeks Internship",
      "Mentor Assistance",
    ],
    buttonText: "Get Pro Learning",
    buttonLink: "https://pages.razorpay.com/pl_NLnxkqJ59E88ih/view",
    maxWidth: "380px",
    maxHeight: "700px",
    minWidth: "380px",
    minHeight: "700px",
  },
  {
    name: "Advanced Learning",
    price: "₹8499",
    originalPrice: "₹16998",
    tag: "MOST POPULAR",
    features: [
      "Training Certificate",
      "Certificate of Internship",
      "Capstone Project",
      "Industry Level Project",
      "6 Weeks Training",
      "6 Weeks Internship",
      "Mentor Assistance",
      "Live Projects",
      "Expert Masterclass",
      "Course Lifetime Access",
      "Community Access",
      "Performance Based LOR",
    ],
    buttonText: "Get Advanced Learning",
    buttonLink: "https://pages.razorpay.com/pl_NLpAiId99vHkKD/view",
    maxWidth: "380px",
    maxHeight: "700px",
    minWidth: "380px",
    minHeight: "700px",
  },
];
