export const DataAnalystAdvanceModule = [
  {
    ModuleName: "Module 1",
    title: "Python Fundamentals and Data Analysis",
    topics: [
      "Python Basics",
      "Data Structures",
      "Libraries",
      "Exploratory Data Analysis (EDA)",
      "Numpy",
      "Pandas",
      "Matplotlib",
      "Advanced Data Handling",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Microsoft Excel for Data Analysis",
    topics: [
      "Excel HOME, Excel Introduction",
      "Excel Get Started, Excel Overview, Excel Syntax, Excel Ranges, Excel Fill, Excel Add Cells",
      "Excel Delete Cells, sheet duplicate, Excel Undo Redo",
      "Excel Arithmetic Operators, Excel Parentheses",
      "Case Studies",
      "Different Test implementation",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Data Visualization with Tableau",
    topics: [
      "Tableau Installation",
      "Overview",
      "Charting Methods",
      "Dashboards",
      "Stories",
      "Filters",
      "Parameters",
      "Graph Options",
    ],
  },
  {
    ModuleName: "Module 4",
    title: "Database Management with SQL",
    topics: [
      "Introduction to SQL - What is SQL & Database",
      "Data Types, Primary -Foreign Keys & Constraints a. Install pgresql and pgadmin4",
      "Create Table in SQL & Create Database",
      "Types of Joins",
      "Subqueries",
      "Terminologies",
      "Hands-on Assignments",
    ],
  },
  {
    ModuleName: "Module 5",
    title: "Data Visualization with Power BI",
    topics: [
      "Power BI Service & Desktop",
      "Tables",
      "Matrix",
      "Charting Methods",
      "Cards",
      "Filters",
      "Slicers",
      "DAX Functions",
      "Dashboard",
    ],
  },
];
export const DataAnalystBasicModule = [
  {
    ModuleName: "Module 1",
    title: "Python Fundamentals and Data Analysis",
    topics: [
      "Python Basics",
      "Data Structures",
      "Libraries",
      "Exploratory Data Analysis (EDA)",
      "Numpy",
      "Pandas",
      "Matplotlib",
      "Advanced Data Handling",
    ],
  },
  {
    ModuleName: "Module 2",
    title: "Microsoft Excel for Data Analysis",
    topics: [
      "Excel HOME, Excel Introduction",
      "Excel Get Started, Excel Overview, Excel Syntax, Excel Ranges, Excel Fill, Excel Add Cells",
      "Excel Delete Cells, sheet duplicate, Excel Undo Redo",
      "Excel Arithmetic Operators, Excel Parentheses",
      "Case Studies",
      "Different Test implementation",
    ],
  },
  {
    ModuleName: "Module 3",
    title: "Data Visualization with Tableau",
    topics: [
      "Tableau Installation",
      "Overview",
      "Charting Methods",
      "Dashboards",
      "Stories",
      "Filters",
      "Parameters",
      "Graph Options",
    ],
  },
];
